### ISSUE TITLE
Нужны еще данные из лога.

### ISSUE THREAD

**Issue by bonvech** [nj-vs-vh/sphere_telemetry_processing#2]
Поскольку пересчет из кодов в давление и температуру местами был неверен, нужно иметь исходные коды датчика давления Pkod и Tkod для перерасчета и проверки.
Они сидят в строке с давлением в квадратных скобках в логах, начиная с марта 2012:

0 Bar:  T[ Tkod0 ] = 30.2 C  P[ Pkod0 ] = 93.64 kPa (9545.3 mm w)
1 Bar:  T[ 33580 ] = 8.6 C  P[ 38267 ] = 95.87 kPa (9773.1 mm w)
 
Пожалуйста, выкусите их в отдельные столбцы Tkod0, Pkod0, Tkod1, Pkod1 типа int.

**Comment by nj-vs-vh** [comment]
Готово! Немного изменил схему парсинга GPS времени, теперь там timestamp выводится как инт, так проще хранить, потом легко преобразовать в строку. Отсутствующие значения помечаются как -1.
