### ISSUE TITLE
Ошибка про EXPECTED_RECORD_LENGTH

### ISSUE THREAD

**Issue by bonvech** [nj-vs-vh/sphere_telemetry_processing#3]
Не все логи парсятся. Некоторые старые логи не расшифровываются.
Например, недавно найденный при археологических раскопках лог log_xx_2010.03.18_to_2012.03.12.txt (уже лежит на гуглодиске) выдает такую ошибку: 

ValueError: Preallocated size for log data is too small, check if EXPECTED_RECORD_LENGTH constant is right for your log (if there are variable-length records, use the shortest)

**Comment by nj-vs-vh** [comment]
Исправил. Для этого лога пришлось поменять алгоритм парсинга, раньше требовался строгий порядок строк внутри записи, но тут есть дополнительная строка с данными GPS, и старый парсер бы сломался. Новый сканирует в поисках каждой строки всю запись, это может быть медленнее, но незначительно. На всякий случай, старая версия сохранена в отдельной ветке `serial_parser`

**Comment by nj-vs-vh** [comment]
По существу ошибки: в коде для скорости используется предвыделение памяти, для этого нужно знать число строк в логе (считается отдельным сканированием) и число строк в записи. Второе число раньше задавалось константой (14 для логов 12 года), и естественно на логах 10 (где это число 7) всё сломалось. Теперь я сделал вычисление этой длины на лету, из первой записи. Правда, всё равно всё может ломаться (если первая запись в логе длинная, а дальше идут короткие, то оцененное число записей будет меньше фактического), тогда можно вручную изменить константу в коде (сейчас она None) и она будет использоваться.
