### ISSUE TITLE
utf-8' codec can't decode byte 0xfe

### ISSUE THREAD

**Issue by bonvech** [nj-vs-vh/sphere_telemetry_processing#5]
При наличии в тексте файла бинарного мусора из буфера GPS парсер ломается на этих символах:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 3672: invalid start byte

Пример такого файла лежит на гуглодиске с именем log1.txt.

![изображение](https://user-images.githubusercontent.com/20185626/84705436-0f822800-af64-11ea-87cf-54d9e95073ea.png)

Можно ли это починить или нужно чистить файл?

**Comment by nj-vs-vh** [comment]
Не удалось воспроизвести эту ошибку. Возможно, при загрузке на гугл драйв все лишние символы сбриваются при сжатии?

**Comment by nj-vs-vh** [comment]
Нашлось возможное решение: вместо встроенного `open` использовать `open` из модуля `codecs`, там есть флаг игнорирования ошибок при кодировании в utf-8. Загружаю коммит.

**Comment by bonvech** [comment]
Скачала с гуглодиска файл log1.txt в другую папку. Та же ошибка. У меня Linux, возможно это имеет значение.
Все бортовые логи для 2010 года расшифровались без проблем?
